In [2]:
pip install requests beautifulsoup4 pandas scikit-learn

Requirement already satisfied: requests in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (4.13.5)
Requirement already satisfied: pandas in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (2.3.1)
Requirement already satisfied: scikit-learn in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

#DATA COLLECTION#

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# domains you want to collect
DOMAINS = {
    "Criminal": "https://indiankanoon.org/search/?formInput=criminal",
    "Civil": "https://indiankanoon.org/search/?formInput=civil",
    "Constitutional": "https://indiankanoon.org/search/?formInput=constitution",
    "Family": "https://indiankanoon.org/search/?formInput=divorce+OR+marriage",
    "Labour": "https://indiankanoon.org/search/?formInput=labour+employment",
    "Taxation": "https://indiankanoon.org/search/?formInput=income+tax+OR+gst",
    "Corporate": "https://indiankanoon.org/search/?formInput=company+law+OR+IBC",
    "IPR": "https://indiankanoon.org/search/?formInput=patent+OR+copyright+OR+trademark",
    "Environmental": "https://indiankanoon.org/search/?formInput=environment+pollution",
}

def get_case_links(base_url, max_pages=2):
    """Fetch case links from Indian Kanoon search pages"""
    links = []
    for page in range(max_pages):
        url = f"{base_url}&pagenum={page}"
        r = requests.get(url)
        soup = BeautifulSoup(r.text, "html.parser")

        for a in soup.select("a"):
            href = a.get("href")
            if href and href.startswith("/doc/"):  # case doc link
                links.append("https://indiankanoon.org" + href)

        time.sleep(2)  # be polite, avoid IP ban
    return list(set(links))

def scrape_case(url):
    """Scrape case text from a single Indian Kanoon case"""
    r = requests.get(url)
    soup = BeautifulSoup(r.text, "html.parser")

    # title
    title = soup.find("h1").get_text(strip=True) if soup.find("h1") else ""

    # judgment text (inside div class 'judgments')
    content = " ".join([p.get_text(" ", strip=True) for p in soup.select("div.judgments p")])
    return title, content

# Collect data per domain
all_data = []
for domain, search_url in DOMAINS.items():
    print(f"Collecting {domain} cases...")
    case_links = get_case_links(search_url, max_pages=3)  # adjust pages

    for link in case_links[:50]:  # limit per domain for demo
        try:
            title, text = scrape_case(link)
            all_data.append({"domain": domain, "title": title, "text": text, "url": link})
        except Exception as e:
            print("Error:", e)
        time.sleep(1)

Collecting Criminal cases...
Collecting Civil cases...
Collecting Constitutional cases...
Collecting Family cases...
Collecting Labour cases...
Collecting Taxation cases...
Collecting Corporate cases...
Collecting IPR cases...
Collecting Environmental cases...
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [4]:
# Save raw dataset
df = pd.DataFrame(all_data)
df.to_csv("indiankanoon_raw.csv", index=False)
print("Saved dataset with", len(df), "cases")

Saved dataset with 303 cases

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# Function to fetch cases for one domain
def fetch_cases(domain, pages_to_scrape=5):
    base_url = "https://indiankanoon.org/search/?formInput="
    cases = []

    print(f"🔹 Fetching cases from {domain.title()} domain...")

    for page in range(0, pages_to_scrape * 20, 10):
        url = f"{base_url}{domain}+doctypes%3Ajudgments&pagenum={page//10 + 1}"
        try:
            response = requests.get(url, timeout=15)
            if response.status_code != 200:
                continue

            soup = BeautifulSoup(response.text, "html.parser")
            results = soup.find_all("div", class_="result_title")

            for res in results:
                case_link = "https://indiankanoon.org" + res.a["href"]
                case_title = res.get_text(strip=True)
                cases.append({"title": case_title, "link": case_link})

        except Exception as e:
            print(f"⚠️ Error fetching page {page//10 + 1} of {domain}: {e}")
            continue

        time.sleep(1)  # gentle pause to avoid server blocking

    # Save cases to CSV
    df = pd.DataFrame(cases)
    df.to_csv(f"{domain}_cases.csv", index=False, encoding="utf-8")

    print(f"✅ Successfully fetched {len(df)} cases from {domain.title()} domain.")
    return df


# 9 Legal Domains (balanced dataset)
domains = [
    "constitutional",
    "criminal",
    "civil",
    "corporate",
    "environmental",
    "family",
    "labour",
    "property",
    "taxation"
]

# Fetch and save data for each domain
all_data = []

for domain in domains:
    df = fetch_cases(domain, pages_to_scrape=25)
    all_data.append(df)

# Combine all domains into one CSV
combined = pd.concat(all_data, ignore_index=True)
combined.to_csv("all_domains_cases.csv", index=False, encoding="utf-8")

print(f"\n🎉 Completed scraping for all domains! Total cases collected: {len(combined)}")

🔹 Fetching cases from Constitutional domain...
⚠️ Error fetching page 31 of constitutional: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
✅ Successfully fetched 380 cases from Constitutional domain.
🔹 Fetching cases from Criminal domain...
✅ Successfully fetched 390 cases from Criminal domain.
🔹 Fetching cases from Civil domain...
✅ Successfully fetched 390 cases from Civil domain.
🔹 Fetching cases from Corporate domain...
✅ Successfully fetched 390 cases from Corporate domain.
🔹 Fetching cases from Environmental domain...
✅ Successfully fetched 390 cases from Environmental domain.
🔹 Fetching cases from Family domain...
✅ Successfully fetched 390 cases from Family domain.
🔹 Fetching cases from Labour domain...
✅ Successfully fetched 390 cases from Labour domain.
🔹 Fetching cases from Property domain...
✅ Successfully fetched 390 cases from Property domain.
🔹 Fetching cases from Taxation domain...
✅ Successfully fetched 390 cases from Taxation domain.

🎉 Completed scraping for all domains! Total cases collected: 3500

In [6]:
import pandas as pd
import glob
import os

# Find all individual domain CSV files
files = glob.glob("*_cases.csv")

dfs = []

for file in files:
    # Extract the domain name from the filename (e.g., "criminal_cases.csv" → "criminal")
    domain_name = os.path.basename(file).replace("_cases.csv", "")
    
    # Read CSV and add domain column
    df = pd.read_csv(file)
    df["domain"] = domain_name
    dfs.append(df)

# Combine all domain DataFrames
combined = pd.concat(dfs, ignore_index=True)

# Save final combined CSV
combined.to_csv("all_domains_cases.csv", index=False, encoding="utf-8")

print(f"✅ Combined {len(files)} domain files into all_domains_cases.csv")
print(f"📄 Total cases combined: {len(combined)}")
print("📁 Added 'domain' column for labeled dataset")

✅ Combined 10 domain files into all_domains_cases.csv
📄 Total cases combined: 7000
📁 Added 'domain' column for labeled dataset

In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import os

# Read the combined CSV
all_cases = pd.read_csv("all_domains_cases.csv")

# Add a new column for full text if it doesn't exist
if "judgment_text" not in all_cases.columns:
    all_cases["judgment_text"] = ""

# Function to fetch full text of a case
def get_full_text(url):
    try:
        response = requests.get(url, timeout=20)
        if response.status_code != 200:
            return ""
        soup = BeautifulSoup(response.text, "html.parser")
        paragraphs = soup.select("div.judgments p")
        text = " ".join([p.get_text(" ", strip=True) for p in paragraphs])
        return text
    except:
        return ""

# Scrape full text for each case
for idx, row in all_cases.iterrows():
    # Skip if text already exists (resume-friendly)
    if row["judgment_text"].strip():
        continue

    all_cases.at[idx, "judgment_text"] = get_full_text(row["link"])
    print(f"Fetched case {idx+1}/{len(all_cases)}: {row['domain']} - {row['title'][:50]}...")

    time.sleep(1)  # polite delay per case

    # Save progress every 50 cases
    if (idx + 1) % 50 == 0:
        all_cases.to_csv("all_domains_cases_fulltext.csv", index=False, encoding="utf-8")
        print(f"💾 Progress saved at case {idx+1}")

# Final save
all_cases.to_csv("all_domains_cases_fulltext.csv", index=False, encoding="utf-8")
print(f"🎉 All cases updated with full judgment text! Total cases: {len(all_cases)}")

Fetched case 1/7000: all_domains - Maneka Gandhi vs Union Of India on 25 January, 197...
Fetched case 2/7000: all_domains - Olga Tellis & Ors vs Bombay Municipal Corporation ...
Fetched case 3/7000: all_domains - Union Of India And Another vs Tulsiram Patel And O...
Fetched case 4/7000: all_domains - A.K. Gopalan vs The State Of Madras.Union Of India...
Fetched case 5/7000: all_domains - Janata Dal vs H.S. Chowdhary And Ors. on 28 August...
Fetched case 6/7000: all_domains - Secretary, State Of Karnataka And ... vs Umadevi A...
Fetched case 7/7000: all_domains - Ajay Hasia Etc vs Khalid Mujib Sehravardi & Ors. E...
Fetched case 8/7000: all_domains - The State Of Bihar vs Maharajadhiraja Sir Kameshwa...
Fetched case 9/7000: all_domains - Central Inland Water ... vs Brojo Nath Ganguly & A...
Fetched case 10/7000: all_domains - Balco Employees Union (Regd.) vs Union Of India & ...
Fetched case 11/7000: all_domains - Tofan Singh vs The State Of Tamil Nadu on 29 Octob...
Fetched case 12/7000: all_domains - Nikesh Tarachand Shah vs Union Of India on 23 Nove...
Fetched case 13/7000: all_domains - Union Of India vs Namit Sharma on 3 September, 201...
Fetched case 14/7000: all_domains - Shafin Jahan vs Asokan K.M. on 8 March, 2018...
Fetched case 15/7000: all_domains - Mafatlal Industries Ltd. And Ors. vs Union Of Indi...
Fetched case 16/7000: all_domains - Mrs. Maneka Gandhi vs Union Of India (Uoi) And Anr...
Fetched case 17/7000: all_domains - Prathvi Raj Chauhan vs Union Of India on 10 Februa...
Fetched case 18/7000: all_domains - Kesavananda Bharati Sripadagalvaru ... vs State Of...
Fetched case 19/7000: all_domains - State Of Uttaranchal vs Balwant Singh Chaufal & Or...
Fetched case 20/7000: all_domains - Navtej Singh Johar vs Union Of India Ministry Of L...
Fetched case 21/7000: all_domains - Unni Krishnan, J.P. And Ors. Etc. Etc vs State Of ...
Fetched case 22/7000: all_domains - M.Nagaraj & Others vs Union Of India & Others on 1...
Fetched case 23/7000: all_domains - Smt. Nilabati Behera Alias Lalit Behera ... vs Sta...
Fetched case 24/7000: all_domains - S.P. Gupta vs Union Of India & Anr on 30 December,...
Fetched case 25/7000: all_domains - Indira Nehru Gandhi vs Shri Raj Narain & Anr on 7 ...
Fetched case 26/7000: all_domains - S.R. Bommai And Others Etc. Etc. vs Union Of India...
Fetched case 27/7000: all_domains - Delhi Transport Corporation vs D.T.C. Mazdoor Cong...
Fetched case 28/7000: all_domains - Ashok Kumar Gupta , Vidya Sagar Gupta & ... vs Sta...
Fetched case 29/7000: all_domains - Bandhua Mukti Morcha vs Union Of India & Others on...
Fetched case 30/7000: all_domains - Ajit Singh And Ors vs State Of Punjab And Ors on 1...
Fetched case 31/7000: all_domains - State Of Bihar vs Upendra Narayan Singh & Ors on 2...
Fetched case 32/7000: all_domains - Government Of Andhra Pradesh & Ors vs Smt. P. Laxm...
Fetched case 33/7000: all_domains - Shakti Vahini vs Union Of India on 27 March, 2018...
Fetched case 34/7000: all_domains - Ashoka Kumar Thakur vs Union Of India & Ors on 10 ...
Fetched case 35/7000: all_domains - Bachan Singh Etc. Etc vs State Of Punjab Etc. Etc ...
Fetched case 36/7000: all_domains - Common Cause, A Registered Society vs Union Of Ind...
Fetched case 37/7000: all_domains - Sukhdev Singh & Ors vs Bagatram Sardar Singh Raghu...
Fetched case 38/7000: all_domains - Noor Aga vs State Of Punjab & Anr on 9 July, 2008...
Fetched case 39/7000: all_domains - State Of Kerala & Anr vs N. M. Thomas & Ors on 19 ...
Fetched case 40/7000: all_domains - Bangalore Water-Supply & Sewerage ... vs R. Rajapp...
Fetched case 41/7000: all_domains - Chiranjit Lal Chowdhuri vs The Union Of India And ...
Fetched case 42/7000: all_domains - P. Ramachandra Rao vs State Of Karnataka on 16 Apr...
Fetched case 43/7000: all_domains - Ashok Kumar Yadav And Ors. Etc. Etc vs State Of Ha...
Fetched case 44/7000: all_domains - Radhy Shyam(D)Thr. Lrs & Ors vs State Of U.P.& Ors...
Fetched case 45/7000: all_domains - A. K. Roy, Etc vs Union Of India And Anr on 28 Dec...
Fetched case 46/7000: all_domains - People'S Union For Civil Liberties & Anr vs Union ...
Fetched case 47/7000: all_domains - The Commissioner, Hindu Religious ... vs Sri Laksh...
Fetched case 48/7000: all_domains - The State Of West Bengal vs Anwar Ali Sarkar on 11...
Fetched case 49/7000: all_domains - Harjinder Singh vs Punjab State Warehousing Corp o...
Fetched case 50/7000: all_domains - Indian Drugs & Pharmaceuticals Ltd vs Workman, Ind...
💾 Progress saved at case 50
Fetched case 51/7000: all_domains - P.A. Inamdar & Ors vs State Of Maharashtra & Ors o...
Fetched case 52/7000: all_domains - Manohar Lal Sharma vs The Principle Secretary & Ot...
Fetched case 53/7000: all_domains - Abdul Rehman Antulay & Ors vs R.S. Nayak & Anr on ...
Fetched case 54/7000: all_domains - R.K. Garg Etc. Etc vs Union Of India & Ors. Etc on...
Fetched case 55/7000: all_domains - Gvk Inds. Ltd & Anr vs The Income Tax Officer & An...
Fetched case 56/7000: all_domains - Radhakrishna Agarwal & Ors vs State Of Bihar & Ors...
Fetched case 57/7000: all_domains - K.M. Abdulla Kunhi And B.L. Abdul Khader vs Union ...
Fetched case 58/7000: all_domains - Synthetics & Chemicals Ltd. Etc vs State Of U.P. A...
Fetched case 59/7000: all_domains - Maharashtra State Road Trans.Corp. ... vs Casterib...
Fetched case 60/7000: all_domains - Chief Justice Of A.P. & Anr vs L.V.A. Dikshitulu &...
Fetched case 61/7000: all_domains - State Of U.P. & Ors.Etc vs Pradhan Sangh Kshettra ...
Fetched case 62/7000: all_domains - Kailash Chand Sharma vs State Of Rajasthan & Ors o...
Fetched case 63/7000: all_domains - The Dharwad Distt. P.W.D. Literate ... vs State Of...
Fetched case 64/7000: all_domains - Monish vs State Of U.P. And 3 Other on 9 February,...
Fetched case 65/7000: all_domains - S.P. Gupta vs President Of India And Ors. on 30 De...
Fetched case 66/7000: all_domains - Supreme Court Advocates-On-Record ... vs Union Of ...
Fetched case 67/7000: all_domains - Justice K.S.Puttaswamy(Retd) And Anr. vs Union Of ...
Fetched case 68/7000: all_domains - Minerva Mills Ltd. & Ors vs Union Of India & Ors o...
Fetched case 69/7000: all_domains - K. Veeraswami vs Union Of India And Others on 25 J...
Fetched case 70/7000: all_domains - Charan Lal Sahu Etc. Etc vs Union Of India And Ors...
Fetched case 71/7000: all_domains - Dr. Subhash Kashinath Mahajan vs The State Of Maha...
Fetched case 72/7000: all_domains - Dr. M. Ismail Faruqui Etc, Mohd. Aslam, ... vs Uni...
Fetched case 73/7000: all_domains - Mohd. Hanif Quareshi & Others vs The State Of Biha...
Fetched case 74/7000: all_domains - People'S Union For Democratic Rights ... vs Union ...
Fetched case 75/7000: all_domains - Public Services Tribunal Bar ... vs State Of U.P. ...
Fetched case 76/7000: all_domains - Francis Coralie Mullin vs The Administrator, Union...
Fetched case 77/7000: all_domains - Common Cause (A Regd. Society) vs Union Of India o...
Fetched case 78/7000: all_domains - Supreme Court Advocates-On-Record ... vs Union Of ...
Fetched case 79/7000: all_domains - Union Of India vs V. Sriharan @ ,Murugan & Ors on ...
Fetched case 80/7000: all_domains - The Ahmedabad St. Xaviers College ... vs State Of ...
Fetched case 81/7000: all_domains - Society For Un-Aided P.School Of Raj vs U.O.I & An...
Fetched case 82/7000: all_domains - The Automobile Transport(Rajasthan) ... vs The Sta...
Fetched case 83/7000: all_domains - Namit Sharma vs Union Of India on 13 September, 20...
Fetched case 84/7000: all_domains - Zee Telefilms Ltd. & Anr vs Union Of India & Ors o...
Fetched case 85/7000: all_domains - Air India Statutory Corporation vs United Labour U...
Fetched case 86/7000: all_domains - R.K. Jain vs Union Of India And Ors on 14 May, 199...
Fetched case 87/7000: all_domains - Bachan Singh vs State Of Punjab on 9 May, 1980...
Fetched case 88/7000: all_domains - Shamsher Singh & Anr vs State Of Punjab on 23 Augu...
Fetched case 89/7000: all_domains - Maru Ram Etc. Etc vs Union Of Lndia & Anr on 11 No...
Fetched case 90/7000: all_domains - Air India Etc. Etc vs Nergesh Meerza & Ors. Etc. E...
Fetched case 91/7000: all_domains - Maharshi Mahesh Jogi ... vs State Of M.P. & Ors on...
Fetched case 92/7000: all_domains - Pramati Educational & Cultural ... vs Union Of Ind...
Fetched case 93/7000: all_domains - Pradeep Kumar Biswas vs Indian Institute Of Chemic...
Fetched case 94/7000: all_domains - M. Karunanidhi vs Union Of India on 20 February, 1...
Fetched case 95/7000: all_domains - Som Prakash Rekhi vs Union Of India & Anr on 13 No...
Fetched case 96/7000: all_domains - The Collector Of Customs, Madras vs Nathella Sampa...
Fetched case 97/7000: all_domains - Miss Mohini Jain vs State Of Karnataka And Ors on ...
Fetched case 98/7000: all_domains - Kasturi Lal Lakshmi Reddy vs State Of Jammu And Ka...
Fetched case 99/7000: all_domains - State Of West Bengal vs Kesoram Industries Ltd. An...
Fetched case 100/7000: all_domains - Swiss Ribbons Pvt. Ltd. vs Union Of India on 25 Ja...
💾 Progress saved at case 100
Fetched case 101/7000: all_domains - Union Carbide Corporation Etc. Etc vs Union Of Ind...
Fetched case 102/7000: all_domains - Basheshar Nath vs The Commissioner Of Income-Tax,D...
Fetched case 103/7000: all_domains - Union Of India vs The State Of Maharashtra on 1 Oc...
Fetched case 104/7000: all_domains - Smt. Triveniben & Ors vs State Of Gujarat & Ors on...
Fetched case 105/7000: all_domains - Bachan Singh, Sher Singh And Anr. And ... vs State...
Fetched case 106/7000: all_domains - Sunil Batra Etc vs Delhi Administration And Ors. E...
Fetched case 107/7000: all_domains - Hoechst Pharmaceuticals Ltd. And ... vs State Of B...
Fetched case 108/7000: all_domains - Federation Of Hotel & Restaurant ... vs Union Of I...
Fetched case 109/7000: all_domains - Union Of India vs Shri Gopal Chandra Misra And Ors...
Fetched case 110/7000: all_domains - Khudiram Das vs The State Of West Bengal & Ors on ...
Fetched case 111/7000: all_domains - Dr. Pradeep Jain Etc vs Union Of India And Ors. Et...
Fetched case 112/7000: all_domains - R. M. D. Chamarbaugwalla vs The Union Of India(Wit...
Fetched case 113/7000: all_domains - H. H. Maharajadhiraja Madhav Rao Jiwaji ... vs Uni...
Fetched case 114/7000: all_domains - State Of Rajasthan & Ors. Etc. Etc vs Union Of Ind...
Fetched case 115/7000: all_domains - Chairman And Managing Director Fci vs Jagdish Bala...
Fetched case 116/7000: all_domains - The State Of West Bengal vs Subodh Gopal Bose And ...
Fetched case 117/7000: all_domains - All India Federation Of Tax ... vs Union Of India ...
Fetched case 118/7000: all_domains - Builders Association Of India & Ors. ... vs Union ...
Fetched case 119/7000: all_domains - State Of Gujarat & Another vs Raman Lal Keshav Lal...
Fetched case 120/7000: all_domains - Ashok Kumar Alias Golu vs Union Of India And Ors o...
Fetched case 121/7000: all_domains - State Of M.P vs Rakesh Kohli & Anr on 11 May, 2012...
Fetched case 122/7000: all_domains - Lakshmi Charan Sen And Ors Etc vs A.K.M. Hassan Uz...
Fetched case 123/7000: all_domains - M. P. Sharma And Others vs Satish Chandra, Distric...
Fetched case 124/7000: all_domains - Vijay Madanlal Choudhary vs Union Of India on 27 J...
Fetched case 125/7000: all_domains - I.C. Golak Nath And Ors. vs State Of Punjab And An...
Fetched case 126/7000: all_domains - Modern Dental College & Res.Cen. & Ors vs State Of...
Fetched case 127/7000: all_domains - Bondu Ramaswamy & Ors vs Bangalore Development Aut...
Fetched case 128/7000: all_domains - Goodyear India Ltd. Etc. Etc vs State Of Haryana &...
Fetched case 129/7000: all_domains - State Of West Bengal vs Union Of India on 21 Decem...
Fetched case 130/7000: all_domains - Sh. Jilubhai Nanbhai Khachar Etc Etc vs State Of G...
Fetched case 131/7000: all_domains - R. S. Joshi, S.T.O. Gujarat Etc. Etc vs Ajit Mills...
Fetched case 132/7000: all_domains - Pooran Mal Etc vs Director Of Inspection ... on 14...
Fetched case 133/7000: all_domains - Deep Chand vs The State Of Uttar Pradeshand ... on...
Fetched case 134/7000: all_domains - Ambika Prasad Mishra Etc vs State Of U.P. And Ors....
Fetched case 135/7000: all_domains - Rama Dhondu Borade vs V.K. Saraf, Commissioner Of ...
Fetched case 136/7000: all_domains - Jagdish Saran & Ors vs Union Of India & Ors on 28 ...
Fetched case 137/7000: all_domains - Dr. D.C. Wadhwa & Ors vs State Of Bihar & Ors on 2...
Fetched case 138/7000: all_domains - Rakesh Kumar Sharma And Ors. vs State Of U.P. And ...
Fetched case 139/7000: all_domains - Sarla Sirohi vs State Of Raj. & Ors on 25 August, ...
Fetched case 140/7000: all_domains - Trashi Agrawal vs The State Of Madhya Pradesh on 1...
Fetched case 141/7000: all_domains - M/S. Vatech Wabag Limited vs Deputy Commissioner O...
Fetched case 142/7000: all_domains - M.P Electricity Production Company vs The State Of...
Fetched case 143/7000: all_domains - Supreme Court Bar Association vs Union Of India & ...
Fetched case 144/7000: all_domains - Santosh Kumar Satishbhushan Bariyar vs State Of Ma...
Fetched case 145/7000: all_domains - M.C. Mehta And Anr vs Union Of India & Ors on 20 D...
Fetched case 146/7000: all_domains - State Of Gujarat vs Mirzapur Moti Kureshi Kassab J...
Fetched case 147/7000: all_domains - Delhi Judicial Service Association Tis ... vs Stat...
Fetched case 148/7000: all_domains - Javed & Ors vs State Of Haryana & Ors on 30 July, ...
Fetched case 149/7000: all_domains - Additional District Magistrate, ... vs Shivakant S...
Fetched case 150/7000: all_domains - Manoj Narula vs Union Of India on 27 August, 2014...
💾 Progress saved at case 150
Fetched case 151/7000: all_domains - Kihoto Hollohan vs Zachillhu And Others on 18 Febr...
Fetched case 152/7000: all_domains - Dr.Subramanian Swamy vs Director, Cbi & Anr on 6 M...
Fetched case 153/7000: all_domains - The Secretary, Ministry Of Information ... vs Cric...
Fetched case 154/7000: all_domains - Nandini Satpathy vs Dani (P.L.) And Anr on 7 April...
Fetched case 155/7000: all_domains - Kavalappara Kottarathil Kochuni And ... vs The Sta...
Fetched case 156/7000: all_domains - Dwarkadas Shrinivas Of Bombay vs The Sholapur Spin...
Fetched case 157/7000: all_domains - Pooja Pal vs Union Of India And Ors on 22 January,...
Fetched case 158/7000: all_domains - Distt. Registrar & Collector, ... vs Canara Bank E...
Fetched case 159/7000: all_domains - E.V.Chinnaiah vs State Of Andhra Pradesh And Ors o...
Fetched case 160/7000: all_domains - Madan Mohan Pathak vs Union Of India & Ors. Etc on...
Fetched case 161/7000: all_domains - Anant Mills Co. Ltd vs State Of Gujarat & Ors on 2...
Fetched case 162/7000: all_domains - Sajjan Singh vs State Of Rajasthan(With Connected ...
Fetched case 163/7000: all_domains - Amarendra Kumar Mohapatra & Ors vs State Of Orissa...
Fetched case 164/7000: all_domains - People'S Union Of Civil Liberties ... vs Union Of ...
Fetched case 165/7000: all_domains - Ahmedabad Municipal Corporation vs Nawab Khan Gula...
Fetched case 166/7000: all_domains - Subramanian Swamy vs Union Of India, Min. Of Law. ...
Fetched case 167/7000: all_domains - State Of Karnataka vs Union Of India & Another on ...
Fetched case 168/7000: all_domains - I. C. Golaknath & Ors vs State Of Punjab & Anrs.(W...
Fetched case 169/7000: all_domains - K.T. Plantation Pvt. Ltd. & Anr vs State Of Karnat...
Fetched case 170/7000: all_domains - Bachan Singh vs State Of Punjab on 9 May, 1980...
Fetched case 171/7000: all_domains - Devender Pal Singh Bhullar & Anr vs State Of Nct O...
Fetched case 172/7000: all_domains - M/S Ashoka Smokeless Coal Ind. P. Ltd. & ... vs Un...
Fetched case 173/7000: all_domains - N.Kannadasan vs Ajoy Khose & Ors on 6 May, 2009...
Fetched case 174/7000: all_domains - All Saints High School, Hyderabad Etc. ... vs Gove...
Fetched case 175/7000: all_domains - K. S. Venkataraman & Co vs State Of Madras on 18 O...
Fetched case 176/7000: all_domains - Maharao Sahib Sri Bhim Singhji Etc. Etc vs Union O...
Fetched case 177/7000: all_domains - Jarnail Singh vs Lachhmi Narain Gupta . on 26 Sept...
Fetched case 178/7000: all_domains - U.P.Power Corp.Ltd vs Rajesh Kumar & Ors on 27 Apr...
Fetched case 179/7000: all_domains - Mohd. Hussain @ Julfikar Ali vs The State (Govt. O...
Fetched case 180/7000: all_domains - Virender Singh Hooda And Ors vs State Of Haryana A...
Fetched case 181/7000: all_domains - Sita Ram & Ors vs State Of U.P on 24 January, 1979...
Fetched case 182/7000: all_domains - Pathumma And Others vs State Of Kerala And Others ...
Fetched case 183/7000: all_domains - Mrs. Valsamma Paul vs Cochin University And Others...
Fetched case 184/7000: all_domains - Cen.Elect.Supply Utility Of Odisha vs Dhobei Sahoo...
Fetched case 185/7000: all_domains - S.P. Sampath Kumar Etc vs Union Of India & Ors on ...
Fetched case 186/7000: all_domains - Dadu @ Tulsidas vs State Of Maharashtra on 12 Octo...
Fetched case 187/7000: all_domains - State Of Karnataka vs Appa Balu Ingale And Others ...
Fetched case 188/7000: all_domains - Lallubhai Jogibhai Patel vs Union Of India & Ors o...
Fetched case 189/7000: all_domains - Kuldip Nayar vs Union Of India & Ors on 22 August,...
Fetched case 190/7000: all_domains - State Of Tamil Nadu vs State Of Kerala & Anr on 7 ...
Fetched case 191/7000: all_domains - Krishna Kumar Singh & Anr vs State Of Bihar & Ors ...
Fetched case 192/7000: all_domains - State Of Karnataka And Anr Etc vs Shri Ranganatha ...
Fetched case 193/7000: all_domains - Commnr.,Central Excise & Customs, ... vs M/S. Lars...
Fetched case 194/7000: all_domains - B.R. Kapoor vs State Of Tamil Nadu And Anr on 21 S...
Fetched case 195/7000: all_domains - B.R. Kapoor vs State Of Tamil Nadu And Anr on 21 S...
Fetched case 196/7000: all_domains - Kapila Hingorani vs State Of Bihar on 9 May, 2003...
Fetched case 197/7000: all_domains - Attorney General For India vs Amratlal Prajivandas...
Fetched case 198/7000: all_domains - Akhil Bharatiya Soshit Karamchari ... vs Union Of ...
Fetched case 199/7000: all_domains - Waman Rao & Ors. Etc. Etc vs Union Of India And Or...
Fetched case 200/7000: all_domains - Rajendra Prasad Etc. Etc vs State Of Uttar Pradesh...
💾 Progress saved at case 200
Fetched case 201/7000: all_domains - Makhan Singh vs State Of Punjab(And Connected Appe...
Fetched case 202/7000: all_domains - Behram Khurshed Pesikaka vs The State Of Bombay.Re...
Fetched case 203/7000: all_domains - B.P. Singhal vs Union Of India & Anr on 7 May, 201...
Fetched case 204/7000: all_domains - Vikas Sankhala & Ors Etc vs Vikas Kumar Agarwal & ...
Fetched case 205/7000: all_domains - Dharam Dutt & Ors vs Union Of India & Ors on 24 No...
Fetched case 206/7000: all_domains - Dattatraya Govind Mahajan & Ors. Etc vs State Of M...
Fetched case 207/7000: all_domains - Ram Sarup vs Munshi And Others(And Connected ... o...
Fetched case 208/7000: all_domains - Union Of India (Uoi) vs Paul Manickam And Anr. on ...
Fetched case 209/7000: all_domains - Nawabkhan Abbaskhan vs The State Of Gujarat on 19 ...
Fetched case 210/7000: all_domains - B. Srinivasa Reddy vs Karnataka Urban Water Supply...
Fetched case 211/7000: all_domains - Deependra Yadav vs The State Of Madhya Pradesh on ...
Fetched case 212/7000: all_domains - S.R. Bommai vs Union Of India on 11 March, 1994...
Fetched case 213/7000: all_domains - Greater Bombay Co-Op. Bank Ltd vs M/S United Yarn ...
Fetched case 214/7000: all_domains - Union Of India (Uoi) vs Sankalchand Himatlal Sheth...
Fetched case 215/7000: all_domains - Bir Singh vs Delhi Jal Board . on 30 August, 2018...
Fetched case 216/7000: all_domains - Sindhi Education Society & Anr vs Chief Secretary,...
Fetched case 217/7000: all_domains - Shri Kihota Hollohon vs Mr. Zachilhu And Others on...
Fetched case 218/7000: all_domains - Usha Bharti vs State Of U.P. & Ors on 28 March, 20...
Fetched case 219/7000: all_domains - Sk Nausad Rahaman vs Union Of India on 10 March, 2...

In [8]:
import pandas as pd

# Load full-text CSV
df = pd.read_csv("all_domains_cases_fulltext.csv")

# Quick cleaning: remove newlines and extra spaces
df["judgment_text"] = df["judgment_text"].str.replace("\n", " ").str.strip()

# Optional: remove rows with empty judgment_text
df = df[df["judgment_text"].str.len() > 50]  # keep cases with text > 50 chars
print(f"✅ Total usable cases: {len(df)}")

✅ Total usable cases: 505

#data preprocessing#

In [9]:
df = pd.read_csv("all_domains_cases_fulltext.csv")  # replace with your 316-case file

# Keep only usable cases (non-empty judgment_text)
usable_df = df[df["judgment_text"].str.strip().str.len() > 50]

# Count number of cases per domain
domain_counts = usable_df["domain"].value_counts()

print("📊 Number of usable cases per domain (316 cases):")
print(domain_counts)

📊 Number of usable cases per domain (316 cases):
domain
all_domains      250
taxation         181
civil             27
corporate         21
criminal           7
family             7
environmental      5
property           5
labour             2
Name: count, dtype: int64

In [10]:
pip install datasets transformers

Requirement already satisfied: datasets in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (4.1.1)
Requirement already satisfied: transformers in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (4.57.0)
Requirement already satisfied: filelock in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (2.0.1)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (2.3.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2025.7.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (0.34.4)
Requirement already satisfied: packaging in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.12.15)
Requirement already satisfied: regex!=2019.12.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.6.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (0.4.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.21.0)
Requirement already satisfied: idna>=2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.10)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.32.2->datasets) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.32.2->datasets) (2025.8.3)
Requirement already satisfied: colorama in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd

df = pd.read_csv("all_domains_cases_fulltext.csv")
print("📄 Columns in your CSV:", df.columns.tolist())
print("\n🔹 Sample rows:")
print(df.head(3))

📄 Columns in your CSV: ['title', 'link', 'domain', 'judgment_text']

🔹 Sample rows:
                                               title  \
0  Maneka Gandhi vs Union Of India on 25 January,...
1  Olga Tellis & Ors vs Bombay Municipal Corporat...
2  Union Of India And Another vs Tulsiram Patel A...

                                                link       domain  \
0  https://indiankanoon.org/docfragment/1766147/?...  all_domains
1  https://indiankanoon.org/docfragment/709776/?f...  all_domains
2  https://indiankanoon.org/docfragment/1134697/?...  all_domains

  judgment_text
0           NaN
1           NaN
2           NaN

In [12]:
import pandas as pd

df = pd.read_csv("all_domains_cases_fulltext.csv")

# Drop rows where text is missing
df = df.dropna(subset=['judgment_text'])

print("✅ Non-empty judgments:", len(df))
print("\n📊 Domain distribution:")
print(df['domain'].value_counts())

✅ Non-empty judgments: 505

📊 Domain distribution:
domain
all_domains      250
taxation         181
civil             27
corporate         21
criminal           7
family             7
environmental      5
property           5
labour             2
Name: count, dtype: int64

In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import AutoTokenizer

# Load and clean
df = pd.read_csv("all_domains_cases_fulltext.csv")
df = df.dropna(subset=['judgment_text', 'domain'])

# Remove any domain with <3 samples
domain_counts = df['domain'].value_counts()
rare_domains = domain_counts[domain_counts < 3].index
df = df[~df['domain'].isin(rare_domains)]

print("✅ Kept domains with ≥3 samples")
print(df['domain'].value_counts())

# Encode labels
label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['domain'])

# Split data safely
if df['label'].value_counts().min() < 2:
    print("⚠️ Not enough data to stratify — using random split.")
    train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)
else:
    train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

# Convert to Hugging Face Datasets
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

# Tokenize
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(example):
    return tokenizer(example["judgment_text"], truncation=True, padding="max_length", max_length=512)

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

print("\n✅ Data ready for model training!")
print(f"Train samples: {len(train_dataset)}")
print(f"Val samples: {len(val_dataset)}")
print(f"Test samples: {len(test_dataset)}")
print("Label mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

✅ Kept domains with ≥3 samples
domain
all_domains      250
taxation         181
civil             27
corporate         21
criminal           7
family             7
environmental      5
property           5
Name: count, dtype: int64

Map: 100%|██████████| 402/402 [00:01<00:00, 235.18 examples/s]
Map: 100%|██████████| 50/50 [00:00<00:00, 108.81 examples/s]
Map: 100%|██████████| 51/51 [00:00<00:00, 171.75 examples/s]

✅ Data ready for model training!
Train samples: 402
Val samples: 50
Test samples: 51
Label mapping: {'all_domains': np.int64(0), 'civil': np.int64(1), 'corporate': np.int64(2), 'criminal': np.int64(3), 'environmental': np.int64(4), 'family': np.int64(5), 'property': np.int64(6), 'taxation': np.int64(7)}

In [14]:
pip install hf_xet

Requirement already satisfied: hf_xet in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (1.1.10)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("all_domains_cases_fulltext.csv")
df = df.dropna(subset=['judgment_text', 'domain'])

# Remove rare domains (<3 samples)
domain_counts = df['domain'].value_counts()
rare_domains = domain_counts[domain_counts < 3].index
df = df[~df['domain'].isin(rare_domains)]

# Encode labels
label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['domain'])
num_labels = len(label_encoder.classes_)
print("Label mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

Label mapping: {'all_domains': np.int64(0), 'civil': np.int64(1), 'corporate': np.int64(2), 'criminal': np.int64(3), 'environmental': np.int64(4), 'family': np.int64(5), 'property': np.int64(6), 'taxation': np.int64(7)}

In [16]:
# Previous mapping:
# {'all_domains': 0, 'civil': 1, 'corporate': 2, 'criminal': 3, 'environmental': 4, 'family': 5, 'property': 6, 'taxation': 7}
num_labels = 8

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=num_labels
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [17]:
pip install --upgrade transformers

Requirement already satisfied: transformers in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (4.57.0)
Collecting transformers
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: filelock in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.34.4)
Requirement already satisfied: numpy>=1.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (2.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: colorama in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (2025.8.3)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.0
    Uninstalling transformers-4.57.0:
      Successfully uninstalled transformers-4.57.0
Successfully installed transformers-4.57.1
Note: you may need to restart the kernel to use updated packages.

In [18]:
import sys
print(sys.executable)

c:\Users\Navya\anaconda3\envs\legal_nlp\python.exe

In [19]:
import transformers
print(transformers.__file__)
print(transformers.__version__)

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\transformers\__init__.py
4.57.0

In [20]:
from transformers import TrainingArguments
print(TrainingArguments)
print(TrainingArguments.__module__)

<class 'transformers.training_args.TrainingArguments'>
transformers.training_args

In [21]:
from transformers import AutoModelForSequenceClassification, Trainer, TrainingArguments

In [22]:
pip install torch

Requirement already satisfied: torch in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (2.8.0)
Requirement already satisfied: filelock in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from torch) (2025.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from jinja2->torch) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [23]:
pip install accelerate>=0.26.0

Note: you may need to restart the kernel to use updated packages.

In [24]:
from transformers import TrainingArguments

try:
    training_args = TrainingArguments(
        output_dir="./outputs",
        num_train_epochs=10,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=16,
        eval_strategy="steps",
        eval_steps=50,
        save_steps=100,
        logging_steps=20,
        learning_rate=2e-5,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="accuracy"
    )
    print("TrainingArguments initialized successfully.")
except ImportError as e:
    print("ImportError:", e)
except Exception as e:
    print("Error:", e)

TrainingArguments initialized successfully.

In [25]:
pip install datasets

Requirement already satisfied: datasets in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (4.1.1)
Requirement already satisfied: filelock in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (2.0.1)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (2.3.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2025.7.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (0.34.4)
Requirement already satisfied: packaging in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.12.15)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (0.4.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.21.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from multidict<7.0,>=4.5->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (4.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.10)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.32.2->datasets) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.32.2->datasets) (2025.8.3)
Requirement already satisfied: colorama in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [26]:
pip install evaluate

Requirement already satisfied: evaluate in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (0.4.6)
Requirement already satisfied: datasets>=2.0.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (4.1.1)
Requirement already satisfied: numpy>=1.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (2.0.1)
Requirement already satisfied: dill in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (0.4.0)
Requirement already satisfied: pandas in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (2.3.1)
Requirement already satisfied: requests>=2.19.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.7.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (0.34.4)
Requirement already satisfied: packaging in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets>=2.0.0->evaluate) (3.19.1)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets>=2.0.0->evaluate) (21.0.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (3.12.15)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.21.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from multidict<7.0,>=4.5->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (4.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (3.10)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.19.0->evaluate) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests>=2.19.0->evaluate) (2025.8.3)
Requirement already satisfied: colorama in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from transformers import Trainer
import evaluate
import numpy as np

# Load accuracy metric
accuracy_metric = evaluate.load("accuracy")

# Define the evaluation metric function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return accuracy_metric.compute(predictions=predictions, references=labels)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

# 🚀 Start training
trainer.train()

C:\Users\Navya\AppData\Local\Temp\ipykernel_17476\1784777584.py:15: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=510, training_loss=1.0077219766729018, metrics={'train_runtime': 11611.4454, 'train_samples_per_second': 0.346, 'train_steps_per_second': 0.044, 'total_flos': 1057763422863360.0, 'train_loss': 1.0077219766729018, 'epoch': 10.0})

In [28]:
# Evaluate on test set
test_results = trainer.evaluate(test_dataset)
print("\n✅ Test Set Evaluation Complete!")
print(test_results)

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

✅ Test Set Evaluation Complete!
{'eval_loss': 1.2807763814926147, 'eval_accuracy': 0.2549019607843137, 'eval_runtime': 24.7101, 'eval_samples_per_second': 2.064, 'eval_steps_per_second': 0.162, 'epoch': 10.0}

In [31]:
import numpy as np
import pandas as pd

# Make predictions
predictions = trainer.predict(test_dataset)
pred_labels = np.argmax(predictions.predictions, axis=1)

# Convert label indices back to domain names
true_domains = label_encoder.inverse_transform(predictions.label_ids)
pred_domains = label_encoder.inverse_transform(pred_labels)

# Create a DataFrame for comparison
results_df = pd.DataFrame({
    "True Domain": true_domains,
    "Predicted Domain": pred_domains
})

# Calculate per-domain accuracy
domain_accuracy = results_df.groupby("True Domain").apply(lambda x: (x["True Domain"] == x["Predicted Domain"]).mean())
print("\n📊 Per-domain accuracy:\n", domain_accuracy)

# Optionally view a few misclassifications
print("\n🔍 Sample misclassifications:")
print(results_df[results_df["True Domain"] != results_df["Predicted Domain"]].head(10))

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

📊 Per-domain accuracy:
 True Domain
all_domains    0.269231
civil          0.000000
corporate      0.000000
criminal       0.000000
family         0.000000
taxation       0.300000
dtype: float64

🔍 Sample misclassifications:
    True Domain Predicted Domain
1      criminal      all_domains
2   all_domains         taxation
3      taxation      all_domains
4   all_domains         taxation
6      taxation      all_domains
7         civil      all_domains
10  all_domains         taxation
11  all_domains         taxation
12  all_domains         taxation
13     taxation      all_domains

C:\Users\Navya\AppData\Local\Temp\ipykernel_17476\3445561975.py:19: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  domain_accuracy = results_df.groupby("True Domain").apply(lambda x: (x["True Domain"] == x["Predicted Domain"]).mean())

In [16]:
from sklearn.utils import resample

df_majority = df[df['domain'] == 'all_domains']
df_minority = df[df['domain'] != 'all_domains']

df_majority_downsampled = resample(
    df_majority,
    replace=False,
    n_samples=min(len(df_majority), len(df_minority)),
    random_state=42
)


df_balanced = pd.concat([df_majority_downsampled, df_minority])

In [7]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(df["domain"])  # or df_balanced["domain"], depending on which DataFrame you're using

LabelEncoder()

In [11]:
print(df.columns)

Index(['title', 'link', 'domain', 'judgment_text'], dtype='object')

In [12]:
# Encode your labels and create a 'label' column in the dataframe
df['label'] = label_encoder.fit_transform(df['domain'])

In [13]:
import torch
from torch.nn import CrossEntropyLoss

# Compute class weights inversely proportional to class frequency
class_weights = torch.tensor(
    [1 / df['label'].value_counts()[i] for i in range(len(label_encoder.classes_))],
    dtype=torch.float
)

loss_fn = CrossEntropyLoss(weight=class_weights)

In [15]:
import pandas as pd
from sklearn.utils import resample
from sklearn.preprocessing import LabelEncoder
import torch
from torch.nn import CrossEntropyLoss

# Load your dataset
df = pd.read_csv("all_domains_cases_fulltext.csv")

# Keep only relevant columns
df = df.dropna(subset=["judgment_text", "domain"])

from sklearn.utils import resample

# Identify majority and minority classes dynamically
domain_counts = df['domain'].value_counts()
majority_class = domain_counts.idxmax()
minority_class = domain_counts.idxmin()

df_majority = df[df['domain'] == majority_class]
df_minority = df[df['domain'] == minority_class]

# Downsample majority to match minority
df_majority_downsampled = resample(
    df_majority,
    replace=False,
    n_samples=len(df_minority),
    random_state=42
)

df_balanced = pd.concat([df_majority_downsampled, df_minority])


df_balanced = pd.concat([df_majority_downsampled, df_minority])

# Encode labels
label_encoder = LabelEncoder()
df_balanced["label"] = label_encoder.fit_transform(df_balanced["domain"])

# Class-weighted loss
class_weights = torch.tensor(
    [1 / df_balanced['label'].value_counts()[i] for i in range(len(label_encoder.classes_))]
)
loss_fn = CrossEntropyLoss(weight=class_weights)

print("✅ df_balanced recreated with shape:", df_balanced.shape)
print("📊 Domain distribution:\n", df_balanced['domain'].value_counts())

✅ df_balanced recreated with shape: (4, 5)
📊 Domain distribution:
 domain
all_domains    2
labour         2
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
from datasets import Dataset

# Count samples per domain
domain_counts = df_balanced['domain'].value_counts()

# Keep only domains that have >= 2 cases
valid_domains = domain_counts[domain_counts >= 2].index
df_balanced = df_balanced[df_balanced['domain'].isin(valid_domains)]

print("✅ Domains with >= 2 cases retained:")
print(df_balanced['domain'].value_counts())

# Encode labels again
label_encoder = LabelEncoder()
df_balanced["label"] = label_encoder.fit_transform(df_balanced["domain"])

# Train-validation split (now safe)
train_df, val_df = train_test_split(
    df_balanced,
    test_size=0.2,
    random_state=42,
    stratify=df_balanced["label"]
)

# Convert to Hugging Face Dataset format
train_dataset = Dataset.from_pandas(train_df[["judgment_text", "label"]])
val_dataset = Dataset.from_pandas(val_df[["judgment_text", "label"]])

print(f"✅ Training samples: {len(train_dataset)} | Validation samples: {len(val_dataset)}")

✅ Domains with >= 2 cases retained:
domain
all_domains      250
taxation         181
civil             27
corporate         21
criminal           7
family             7
environmental      5
property           5
labour             2
Name: count, dtype: int64
✅ Training samples: 404 | Validation samples: 101

In [ ]:
pip install -U transformers

Requirement already satisfied: transformers in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (4.57.1)
Requirement already satisfied: filelock in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.34.4)
Requirement already satisfied: numpy>=1.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (2.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: colorama in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

In [18]:
print(df_balanced.columns)

Index(['title', 'link', 'domain', 'judgment_text', 'label'], dtype='object')

In [ ]:
import transformers
print(transformers.__version__)

4.57.0

In [29]:
!pip uninstall transformers -y
!pip install transformers==4.57.0

Found existing installation: transformers 4.57.1
Uninstalling transformers-4.57.1:
  Successfully uninstalled transformers-4.57.1
Collecting transformers==4.57.0
  Using cached transformers-4.57.0-py3-none-any.whl.metadata (41 kB)
Requirement already satisfied: filelock in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (0.34.4)
Requirement already satisfied: numpy>=1.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (2.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (2024.11.6)
Requirement already satisfied: requests in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from transformers==4.57.0) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.0) (2025.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.0) (4.15.0)
Requirement already satisfied: colorama in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from tqdm>=4.27->transformers==4.57.0) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers==4.57.0) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers==4.57.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers==4.57.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\navya\anaconda3\envs\legal_nlp\lib\site-packages (from requests->transformers==4.57.0) (2025.8.3)
Using cached transformers-4.57.0-py3-none-any.whl (12.0 MB)
Installing collected packages: transformers
Successfully installed transformers-4.57.0

WARNING: The candidate selected for download or install is a yanked version: 'transformers' candidate (version 4.57.0 at https://files.pythonhosted.org/packages/e5/2b/4d2708ac1ff5cd708b6548f4c5812d0ae40d1c28591c4c1c762b6dbdef2d/transformers-4.57.0-py3-none-any.whl (from https://pypi.org/simple/transformers/) (requires-python:>=3.9.0))
Reason for being yanked: Error in the setup causing installation issues

In [28]:
from transformers import TrainingArguments
help(TrainingArguments)

Help on class TrainingArguments in module transformers.training_args:

class TrainingArguments(builtins.object)
 |  TrainingArguments(output_dir: Optional[str] = None, overwrite_output_dir: bool = False, do_train: bool = False, do_eval: bool = False, do_predict: bool = False, eval_strategy: Union[transformers.trainer_utils.IntervalStrategy, str] = 'no', prediction_loss_only: bool = False, per_device_train_batch_size: int = 8, per_device_eval_batch_size: int = 8, per_gpu_train_batch_size: Optional[int] = None, per_gpu_eval_batch_size: Optional[int] = None, gradient_accumulation_steps: int = 1, eval_accumulation_steps: Optional[int] = None, eval_delay: float = 0, torch_empty_cache_steps: Optional[int] = None, learning_rate: float = 5e-05, weight_decay: float = 0.0, adam_beta1: float = 0.9, adam_beta2: float = 0.999, adam_epsilon: float = 1e-08, max_grad_norm: float = 1.0, num_train_epochs: float = 3.0, max_steps: int = -1, lr_scheduler_type: Union[transformers.trainer_utils.SchedulerType, str] = 'linear', lr_scheduler_kwargs: Union[dict[str, Any], str] = <factory>, warmup_ratio: float = 0.0, warmup_steps: int = 0, log_level: str = 'passive', log_level_replica: str = 'warning', log_on_each_node: bool = True, logging_dir: Optional[str] = None, logging_strategy: Union[transformers.trainer_utils.IntervalStrategy, str] = 'steps', logging_first_step: bool = False, logging_steps: float = 500, logging_nan_inf_filter: bool = True, save_strategy: Union[transformers.trainer_utils.SaveStrategy, str] = 'steps', save_steps: float = 500, save_total_limit: Optional[int] = None, save_safetensors: bool = True, save_on_each_node: bool = False, save_only_model: bool = False, restore_callback_states_from_checkpoint: bool = False, no_cuda: bool = False, use_cpu: bool = False, use_mps_device: bool = False, seed: int = 42, data_seed: Optional[int] = None, jit_mode_eval: bool = False, bf16: bool = False, fp16: bool = False, fp16_opt_level: str = 'O1', half_precision_backend: str = 'auto', bf16_full_eval: bool = False, fp16_full_eval: bool = False, tf32: Optional[bool] = None, local_rank: int = -1, ddp_backend: Optional[str] = None, tpu_num_cores: Optional[int] = None, tpu_metrics_debug: bool = False, debug: Union[str, list[transformers.debug_utils.DebugOption]] = '', dataloader_drop_last: bool = False, eval_steps: Optional[float] = None, dataloader_num_workers: int = 0, dataloader_prefetch_factor: Optional[int] = None, past_index: int = -1, run_name: Optional[str] = None, disable_tqdm: Optional[bool] = None, remove_unused_columns: bool = True, label_names: Optional[list[str]] = None, load_best_model_at_end: bool = False, metric_for_best_model: Optional[str] = None, greater_is_better: Optional[bool] = None, ignore_data_skip: bool = False, fsdp: Union[list[transformers.trainer_utils.FSDPOption], str, NoneType] = None, fsdp_min_num_params: int = 0, fsdp_config: Union[dict[str, Any], str, NoneType] = None, fsdp_transformer_layer_cls_to_wrap: Optional[str] = None, accelerator_config: Union[dict, str, NoneType] = None, parallelism_config: Optional[accelerate.parallelism_config.ParallelismConfig] = None, deepspeed: Union[dict, str, NoneType] = None, label_smoothing_factor: float = 0.0, optim: Union[transformers.training_args.OptimizerNames, str] = 'adamw_torch_fused', optim_args: Optional[str] = None, adafactor: bool = False, group_by_length: bool = False, length_column_name: str = 'length', report_to: Union[NoneType, str, list[str]] = None, project: str = 'huggingface', trackio_space_id: Optional[str] = 'trackio', ddp_find_unused_parameters: Optional[bool] = None, ddp_bucket_cap_mb: Optional[int] = None, ddp_broadcast_buffers: Optional[bool] = None, dataloader_pin_memory: bool = True, dataloader_persistent_workers: bool = False, skip_memory_metrics: bool = True, use_legacy_prediction_loop: bool = False, push_to_hub: bool = False, resume_from_checkpoint: Optional[str] = None, hub_model_id: Optional[str] = None, hub_strategy: Union[transformers.trainer_utils.HubStrategy, str] = 'every_save', hub_token: Optional[str] = None, hub_private_repo: Optional[bool] = None, hub_always_push: bool = False, hub_revision: Optional[str] = None, gradient_checkpointing: bool = False, gradient_checkpointing_kwargs: Union[dict[str, Any], str, NoneType] = None, include_inputs_for_metrics: bool = False, include_for_metrics: list[str] = <factory>, eval_do_concat_batches: bool = True, fp16_backend: str = 'auto', push_to_hub_model_id: Optional[str] = None, push_to_hub_organization: Optional[str] = None, push_to_hub_token: Optional[str] = None, mp_parameters: str = '', auto_find_batch_size: bool = False, full_determinism: bool = False, torchdynamo: Optional[str] = None, ray_scope: Optional[str] = 'last', ddp_timeout: int = 1800, torch_compile: bool = False, torch_compile_backend: Optional[str] = None, torch_compile_mode: Optional[str] = None, include_tokens_per_second: bool = False, include_num_input_tokens_seen: Union[str, bool] = False, neftune_noise_alpha: Optional[float] = None, optim_target_modules: Union[NoneType, str, list[str]] = None, batch_eval_metrics: bool = False, eval_on_start: bool = False, use_liger_kernel: bool = False, liger_kernel_config: Optional[dict[str, bool]] = None, eval_use_gather_object: bool = False, average_tokens_across_devices: bool = True) -> None
 |
 |  TrainingArguments is the subset of the arguments we use in our example scripts **which relate to the training loop
 |  itself**.
 |
 |  Using [`HfArgumentParser`] we can turn this class into
 |  [argparse](https://docs.python.org/3/library/argparse#module-argparse) arguments that can be specified on the
 |  command line.
 |
 |  Parameters:
 |      output_dir (`str`, *optional*, defaults to `"trainer_output"`):
 |          The output directory where the model predictions and checkpoints will be written.
 |      overwrite_output_dir (`bool`, *optional*, defaults to `False`):
 |          If `True`, overwrite the content of the output directory. Use this to continue training if `output_dir`
 |          points to a checkpoint directory.
 |      do_train (`bool`, *optional*, defaults to `False`):
 |          Whether to run training or not. This argument is not directly used by [`Trainer`], it's intended to be used
 |          by your training/evaluation scripts instead. See the [example
 |          scripts](https://github.com/huggingface/transformers/tree/main/examples) for more details.
 |      do_eval (`bool`, *optional*):
 |          Whether to run evaluation on the validation set or not. Will be set to `True` if `eval_strategy` is
 |          different from `"no"`. This argument is not directly used by [`Trainer`], it's intended to be used by your
 |          training/evaluation scripts instead. See the [example
 |          scripts](https://github.com/huggingface/transformers/tree/main/examples) for more details.
 |      do_predict (`bool`, *optional*, defaults to `False`):
 |          Whether to run predictions on the test set or not. This argument is not directly used by [`Trainer`], it's
 |          intended to be used by your training/evaluation scripts instead. See the [example
 |          scripts](https://github.com/huggingface/transformers/tree/main/examples) for more details.
 |      eval_strategy (`str` or [`~trainer_utils.IntervalStrategy`], *optional*, defaults to `"no"`):
 |          The evaluation strategy to adopt during training. Possible values are:
 |
 |              - `"no"`: No evaluation is done during training.
 |              - `"steps"`: Evaluation is done (and logged) every `eval_steps`.
 |              - `"epoch"`: Evaluation is done at the end of each epoch.
 |
 |      prediction_loss_only (`bool`, *optional*, defaults to `False`):
 |          When performing evaluation and generating predictions, only returns the loss.
 |      per_device_train_batch_size (`int`, *optional*, defaults to 8):
 |          The batch size *per device*. The **global batch size** is computed as:
 |          `per_device_train_batch_size * number_of_devices` in multi-GPU or distributed setups.
 |      per_device_eval_batch_size (`int`, *optional*, defaults to 8):
 |          The batch size per device accelerator core/CPU for evaluation.
 |      gradient_accumulation_steps (`int`, *optional*, defaults to 1):
 |          Number of updates steps to accumulate the gradients for, before performing a backward/update pass.
 |
 |          <Tip warning={true}>
 |
 |          When using gradient accumulation, one step is counted as one step with backward pass. Therefore, logging,
 |          evaluation, save will be conducted every `gradient_accumulation_steps * xxx_step` training examples.
 |
 |          </Tip>
 |
 |      eval_accumulation_steps (`int`, *optional*):
 |          Number of predictions steps to accumulate the output tensors for, before moving the results to the CPU. If
 |          left unset, the whole predictions are accumulated on the device accelerator before being moved to the CPU (faster but
 |          requires more memory).
 |      eval_delay (`float`, *optional*):
 |          Number of epochs or steps to wait for before the first evaluation can be performed, depending on the
 |          eval_strategy.
 |      torch_empty_cache_steps (`int`, *optional*):
 |          Number of steps to wait before calling `torch.<device>.empty_cache()`. If left unset or set to None, cache will not be emptied.
 |
 |          <Tip>
 |
 |          This can help avoid CUDA out-of-memory errors by lowering peak VRAM usage at a cost of about [10% slower performance](https://github.com/huggingface/transformers/issues/31372).
 |
 |          </Tip>
 |
 |      learning_rate (`float`, *optional*, defaults to 5e-5):
 |          The initial learning rate for [`AdamW`] optimizer.
 |      weight_decay (`float`, *optional*, defaults to 0):
 |          The weight decay to apply (if not zero) to all layers except all bias and LayerNorm weights in [`AdamW`]
 |          optimizer.
 |      adam_beta1 (`float`, *optional*, defaults to 0.9):
 |          The beta1 hyperparameter for the [`AdamW`] optimizer.
 |      adam_beta2 (`float`, *optional*, defaults to 0.999):
 |          The beta2 hyperparameter for the [`AdamW`] optimizer.
 |      adam_epsilon (`float`, *optional*, defaults to 1e-8):
 |          The epsilon hyperparameter for the [`AdamW`] optimizer.
 |      max_grad_norm (`float`, *optional*, defaults to 1.0):
 |          Maximum gradient norm (for gradient clipping).
 |      num_train_epochs(`float`, *optional*, defaults to 3.0):
 |          Total number of training epochs to perform (if not an integer, will perform the decimal part percents of
 |          the last epoch before stopping training).
 |      max_steps (`int`, *optional*, defaults to -1):
 |          If set to a positive number, the total number of training steps to perform. Overrides `num_train_epochs`.
 |          For a finite dataset, training is reiterated through the dataset (if all data is exhausted) until
 |          `max_steps` is reached.
 |      lr_scheduler_type (`str` or [`SchedulerType`], *optional*, defaults to `"linear"`):
 |          The scheduler type to use. See the documentation of [`SchedulerType`] for all possible values.
 |      lr_scheduler_kwargs ('dict', *optional*, defaults to {}):
 |          The extra arguments for the lr_scheduler. See the documentation of each scheduler for possible values.
 |      warmup_ratio (`float`, *optional*, defaults to 0.0):
 |          Ratio of total training steps used for a linear warmup from 0 to `learning_rate`.
 |      warmup_steps (`int`, *optional*, defaults to 0):
 |          Number of steps used for a linear warmup from 0 to `learning_rate`. Overrides any effect of `warmup_ratio`.
 |      log_level (`str`, *optional*, defaults to `passive`):
 |          Logger log level to use on the main process. Possible choices are the log levels as strings: 'debug',
 |          'info', 'warning', 'error' and 'critical', plus a 'passive' level which doesn't set anything and keeps the
 |          current log level for the Transformers library (which will be `"warning"` by default).
 |      log_level_replica (`str`, *optional*, defaults to `"warning"`):
 |          Logger log level to use on replicas. Same choices as `log_level`"
 |      log_on_each_node (`bool`, *optional*, defaults to `True`):
 |          In multinode distributed training, whether to log using `log_level` once per node, or only on the main
 |          node.
 |      logging_dir (`str`, *optional*):
 |          [TensorBoard](https://www.tensorflow.org/tensorboard) log directory. Will default to
 |          *output_dir/runs/**CURRENT_DATETIME_HOSTNAME***.
 |      logging_strategy (`str` or [`~trainer_utils.IntervalStrategy`], *optional*, defaults to `"steps"`):
 |          The logging strategy to adopt during training. Possible values are:
 |
 |              - `"no"`: No logging is done during training.
 |              - `"epoch"`: Logging is done at the end of each epoch.
 |              - `"steps"`: Logging is done every `logging_steps`.
 |
 |      logging_first_step (`bool`, *optional*, defaults to `False`):
 |          Whether to log the first `global_step` or not.
 |      logging_steps (`int` or `float`, *optional*, defaults to 500):
 |          Number of update steps between two logs if `logging_strategy="steps"`. Should be an integer or a float in
 |          range `[0,1)`. If smaller than 1, will be interpreted as ratio of total training steps.
 |      logging_nan_inf_filter (`bool`, *optional*, defaults to `True`):
 |          Whether to filter `nan` and `inf` losses for logging. If set to `True` the loss of every step that is `nan`
 |          or `inf` is filtered and the average loss of the current logging window is taken instead.
 |
 |          <Tip>
 |
 |          `logging_nan_inf_filter` only influences the logging of loss values, it does not change the behavior the
 |          gradient is computed or applied to the model.
 |
 |          </Tip>
 |
 |      save_strategy (`str` or [`~trainer_utils.SaveStrategy`], *optional*, defaults to `"steps"`):
 |          The checkpoint save strategy to adopt during training. Possible values are:
 |
 |              - `"no"`: No save is done during training.
 |              - `"epoch"`: Save is done at the end of each epoch.
 |              - `"steps"`: Save is done every `save_steps`.
 |              - `"best"`: Save is done whenever a new `best_metric` is achieved.
 |
 |              If `"epoch"` or `"steps"` is chosen, saving will also be performed at the
 |              very end of training, always.
 |      save_steps (`int` or `float`, *optional*, defaults to 500):
 |          Number of updates steps before two checkpoint saves if `save_strategy="steps"`. Should be an integer or a
 |          float in range `[0,1)`. If smaller than 1, will be interpreted as ratio of total training steps.
 |      save_total_limit (`int`, *optional*):
 |          If a value is passed, will limit the total amount of checkpoints. Deletes the older checkpoints in
 |          `output_dir`. When `load_best_model_at_end` is enabled, the "best" checkpoint according to
 |          `metric_for_best_model` will always be retained in addition to the most recent ones. For example, for
 |          `save_total_limit=5` and `load_best_model_at_end`, the four last checkpoints will always be retained
 |          alongside the best model. When `save_total_limit=1` and `load_best_model_at_end`, it is possible that two
 |          checkpoints are saved: the last one and the best one (if they are different).
 |      save_safetensors (`bool`, *optional*, defaults to `True`):
 |          Use [safetensors](https://huggingface.co/docs/safetensors) saving and loading for state dicts instead of
 |          default `torch.load` and `torch.save`.
 |      save_on_each_node (`bool`, *optional*, defaults to `False`):
 |          When doing multi-node distributed training, whether to save models and checkpoints on each node, or only on
 |          the main one.
 |
 |          This should not be activated when the different nodes use the same storage as the files will be saved with
 |          the same names for each node.
 |      save_only_model (`bool`, *optional*, defaults to `False`):
 |          When checkpointing, whether to only save the model, or also the optimizer, scheduler & rng state.
 |          Note that when this is true, you won't be able to resume training from checkpoint.
 |          This enables you to save storage by not storing the optimizer, scheduler & rng state.
 |          You can only load the model using `from_pretrained` with this option set to `True`.
 |      restore_callback_states_from_checkpoint (`bool`, *optional*, defaults to `False`):
 |          Whether to restore the callback states from the checkpoint. If `True`, will override
 |          callbacks passed to the `Trainer` if they exist in the checkpoint."
 |      use_cpu (`bool`, *optional*, defaults to `False`):
 |          Whether or not to use cpu. If set to False, we will use cuda or mps device if available.
 |      seed (`int`, *optional*, defaults to 42):
 |          Random seed that will be set at the beginning of training. To ensure reproducibility across runs, use the
 |          [`~Trainer.model_init`] function to instantiate the model if it has some randomly initialized parameters.
 |      data_seed (`int`, *optional*):
 |          Random seed to be used with data samplers. If not set, random generators for data sampling will use the
 |          same seed as `seed`. This can be used to ensure reproducibility of data sampling, independent of the model
 |          seed.
 |      jit_mode_eval (`bool`, *optional*, defaults to `False`):
 |          Whether or not to use PyTorch jit trace for inference.
 |      bf16 (`bool`, *optional*, defaults to `False`):
 |          Whether to use bf16 16-bit (mixed) precision training instead of 32-bit training. Requires Ampere or higher
 |          NVIDIA architecture or Intel XPU or using CPU (use_cpu) or Ascend NPU.
 |      fp16 (`bool`, *optional*, defaults to `False`):
 |          Whether to use fp16 16-bit (mixed) precision training instead of 32-bit training.
 |      fp16_opt_level (`str`, *optional*, defaults to 'O1'):
 |          For `fp16` training, Apex AMP optimization level selected in ['O0', 'O1', 'O2', and 'O3']. See details on
 |          the [Apex documentation](https://nvidia.github.io/apex/amp).
 |      fp16_backend (`str`, *optional*, defaults to `"auto"`):
 |          This argument is deprecated. Use `half_precision_backend` instead.
 |      half_precision_backend (`str`, *optional*, defaults to `"auto"`):
 |          The backend to use for mixed precision training. Must be one of `"auto", "apex", "cpu_amp"`. `"auto"` will
 |          use CPU/CUDA AMP or APEX depending on the PyTorch version detected, while the other choices will force the
 |          requested backend.
 |      bf16_full_eval (`bool`, *optional*, defaults to `False`):
 |          Whether to use full bfloat16 evaluation instead of 32-bit. This will be faster and save memory but can harm
 |          metric values.
 |      fp16_full_eval (`bool`, *optional*, defaults to `False`):
 |          Whether to use full float16 evaluation instead of 32-bit. This will be faster and save memory but can harm
 |          metric values.
 |      tf32 (`bool`, *optional*):
 |          Whether to enable the TF32 mode, available in Ampere and newer GPU architectures. The default value depends
 |          on PyTorch's version default of `torch.backends.cuda.matmul.allow_tf32`. For more details please refer to
 |          the [TF32](https://huggingface.co/docs/transformers/perf_train_gpu_one#tf32) documentation. This is an
 |          experimental API and it may change.
 |      local_rank (`int`, *optional*, defaults to -1):
 |          Rank of the process during distributed training.
 |      ddp_backend (`str`, *optional*):

In [27]:
import transformers
print(transformers.__file__)

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\transformers\__init__.py

In [19]:
print(train_dataset.column_names)
print(val_dataset.column_names)

['judgment_text', 'label', '__index_level_0__']
['judgment_text', 'label', '__index_level_0__']

In [20]:
def tokenize_function(example):
    return tokenizer(example["judgement_text"], padding="max_length", truncation=True, max_length=512)

In [37]:
def tokenize_function(example):
    return tokenizer(example["judgement_text"], padding="max_length", truncation=True, max_length=1024)

In [38]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("law-ai/InLegalBERT")

def tokenize_function(example):
    return tokenizer(example["judgment_text"], padding="max_length", truncation=True, max_length=1024)

In [39]:
train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)

Map: 100%|██████████| 404/404 [00:02<00:00, 166.58 examples/s]
Map: 100%|██████████| 101/101 [00:00<00:00, 117.85 examples/s]

In [40]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.preprocessing import LabelEncoder
import torch
import numpy as np

# -----------------------------
# Step 1: Tokenizer
# -----------------------------
tokenizer = AutoTokenizer.from_pretrained("law-ai/InLegalBERT")

def tokenize_function(example):
    return tokenizer(example["judgment_text"], padding="max_length", truncation=True, max_length=512)

# Tokenize datasets
train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)

# -----------------------------
# Step 2: Ensure labels column exists
# -----------------------------
# Copy 'label' to 'labels' for Trainer compatibility
train_dataset = train_dataset.map(lambda x: {"labels": x["label"]})
val_dataset = val_dataset.map(lambda x: {"labels": x["label"]})

# -----------------------------
# Step 3: Load Model
# -----------------------------
model = AutoModelForSequenceClassification.from_pretrained(
    "law-ai/InLegalBERT",
    num_labels=len(np.unique(train_dataset["label"]))
)

# -----------------------------
# Step 4: Training Arguments
# -----------------------------
training_args = TrainingArguments(
    output_dir="./results_inlegalbert",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,
    num_train_epochs=10,
    weight_decay=0.01,
    logging_dir="./logs_inlegalbert",
    logging_steps=50,
    save_total_limit=2,
    eval_strategy="steps",  # ✅ works in 4.57
    eval_steps=50
)


# -----------------------------
# Step 5: Custom Trainer (Weighted Loss)
# -----------------------------
class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # Automatically compute class weights
        classes = np.unique(train_dataset["label"])
        counts = np.bincount(train_dataset["label"])
        weight = torch.tensor([len(train_dataset)/counts[i] for i in classes], dtype=torch.float).to(logits.device)

        loss_fct = torch.nn.CrossEntropyLoss(weight=weight)
        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

# -----------------------------
# Step 6: Trainer Initialization
# -----------------------------
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer
)

# -----------------------------
# Step 7: Train the model
# -----------------------------
trainer.train()

Map: 100%|██████████| 404/404 [00:01<00:00, 228.37 examples/s]
Map: 100%|██████████| 101/101 [00:00<00:00, 110.75 examples/s]
Map: 100%|██████████| 404/404 [00:00<00:00, 6758.34 examples/s]
Map: 100%|██████████| 101/101 [00:00<00:00, 3996.12 examples/s]
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at law-ai/InLegalBERT and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\Navya\AppData\Local\Temp\ipykernel_21404\3732155101.py:73: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `CustomTrainer.__init__`. Use `processing_class` instead.
  trainer = CustomTrainer(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=1010, training_loss=1.287367562020179, metrics={'train_runtime': 12421.9819, 'train_samples_per_second': 0.325, 'train_steps_per_second': 0.081, 'total_flos': 1063035471421440.0, 'train_loss': 1.287367562020179, 'epoch': 10.0})

In [41]:
results = trainer.evaluate()
print(results)

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

{'eval_loss': 2.186776638031006, 'eval_runtime': 51.6377, 'eval_samples_per_second': 1.956, 'eval_steps_per_second': 0.252, 'epoch': 10.0}

In [42]:
trainer.save_model("inlegal_bert")
tokenizer.save_pretrained("inlegal_bert")

('inlegal_bert\\tokenizer_config.json',
 'inlegal_bert\\special_tokens_map.json',
 'inlegal_bert\\vocab.txt',
 'inlegal_bert\\added_tokens.json',
 'inlegal_bert\\tokenizer.json')

In [43]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="inlegal_bert",
    tokenizer="inlegal_bert"
)

example_text = "The company violated the contract terms."
print(classifier(example_text))

Device set to use cpu

[{'label': 'LABEL_0', 'score': 0.33082395792007446}]

In [44]:
# Define the class names in the same order as your labels (0–7)
label_names = [
    "Civil", "Corporate", "Family", "Taxation",
    "Criminal", "Labour", "Property", "Other"
]

In [45]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="legal_bert_finetuned",
    tokenizer="legal_bert_finetuned",
    device=-1  # CPU; use device=0 for GPU
)

example_text = "The company violated the contract terms."
result = classifier(example_text)[0]

# Map LABEL_# to class name
label_index = int(result['label'].split("_")[-1])
result['label'] = label_names[label_index]

print(result)

Device set to use cpu

{'label': 'Other', 'score': 0.17183460295200348}

In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = r"C:\Users\Navya\Desktop\navya lap\College\SEM5\NLP\Project\inlegal_bert"
model = AutoModelForSequenceClassification.from_pretrained(model_path)

print(model.config.id2label)

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2', 3: 'LABEL_3', 4: 'LABEL_4', 5: 'LABEL_5', 6: 'LABEL_6', 7: 'LABEL_7', 8: 'LABEL_8'}

In [3]:
from transformers import AutoModelForSequenceClassification
import os

old_path = r"C:\Users\Navya\Desktop\navya lap\College\SEM5\NLP\Project\inlegal_bert"
new_path = os.path.join(os.path.dirname(old_path), "inlegal_bert_updated")

model = AutoModelForSequenceClassification.from_pretrained(old_path)

model.config.id2label = {
    0: "Civil",
    1: "Corporate",
    2: "Family",
    3: "Taxation",
    4: "Criminal",
    5: "Labour",
    6: "Property",
    7: "Other",
    8: "Miscellaneous"
}
model.config.label2id = {v: k for k, v in model.config.id2label.items()}

model.save_pretrained(new_path)
print(f"✅ Model label mapping saved successfully to {new_path}")

✅ Model label mapping saved successfully to C:\Users\Navya\Desktop\navya lap\College\SEM5\NLP\Project\inlegal_bert_updated

In [1]:
from transformers import AutoConfig
config = AutoConfig.from_pretrained(r"C:\Users\Navya\Desktop\navya lap\College\SEM5\NLP\Project\inlegal_bert")
print(config.id2label)

c:\Users\Navya\anaconda3\envs\legal_nlp\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

{0: 'Civil', 1: 'Corporate', 2: 'Family', 3: 'Taxation', 4: 'Criminal', 5: 'Labour', 6: 'Property', 7: 'Other', 8: 'Miscellaneous'}